"""Add role to User model

Revision ID: 1a11bf6182b2
Revises: f5062b254a53
Create Date: 2025-09-21 03:04:37.942935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '1a11bf6182b2'
down_revision = 'f5062b254a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semantic_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('soft_score')
        batch_op.drop_column('evaluated_at')
        batch_op.drop_column('evaluator_version')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.drop_column('min_experience_years')
        batch_op.drop_column('good_to_have')
        batch_op.drop_column('min_education')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_student_id'))
        batch_op.drop_column('student_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_resumes_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('min_education', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('good_to_have', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('min_experience_years', sa.INTEGER(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evaluator_version', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('evaluated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('soft_score', sa.FLOAT(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('semantic_score')

    # ### end Alembic commands ###
