"""Initial migration.

Revision ID: 77ca31aba752
Revises: 
Create Date: 2025-09-20 11:46:18.142748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ca31aba752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_jd_text', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('good_to_have', sa.JSON(), nullable=True),
    sa.Column('min_education', sa.String(length=100), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('original_file_uri', sa.String(length=500), nullable=False),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_student_id'), ['student_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('hard_score', sa.Float(), nullable=True),
    sa.Column('soft_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=100), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('evaluator_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_final_score'), ['final_score'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_final_score'))

    op.drop_table('evaluations')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_student_id'))

    op.drop_table('resumes')
    op.drop_table('jobs')
    # ### end Alembic commands ###
